// <auto-generated />
namespace CodeWork.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddSkillLevelIdToUserSkills : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSkillLevelIdToUserSkills));
        
        string IMigrationMetadata.Id
        {
            get { return "202007070938455_AddSkillLevelIdToUserSkills"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
